---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      name: laravel
  template:
    metadata:
      labels:
        name: laravel
    spec:
      containers:
      - name: laravel
        image: steveoliver/laravel-roadrunner:v0.0.8
        command: ["rr"]
        args: ["serve"]
        volumes:
          - tmp-data:/tmp:rw
        ports:
        - containerPort: 8080
          name: laravel-port
        envFrom:
        - secretRef:
            name: laravel-secrets
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: laravel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: laravel-port
  selector:
    name: laravel
