---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      name: laravel
  template:
    metadata:
      labels:
        name: laravel
    spec:
      containers:
      - name: laravel
        image: steveoliver/laravel-roadrunner:v0.0.4
        command: ["rr"]
        args: ["serve", "-c", ".rr.yaml"]
        volumes:
          - /etc/passwd:/etc/passwd:ro
          - /etc/group:/etc/group:ro
          - tmp-data:/tmp:rw
          - .:/app:rw
#         resources:
#           limits:
#             cpu: 300m
#             memory: 1000Mi
#           requests:
#             cpu: 100m
#             memory: 300Mi
        ports:
        - containerPort: 8080
        env:
        - name: HOME
          value: /tmp
#         - name: RR_RELAY
#           value: pipes
        - name: APP_KEY
          value: base64:cUPmwHx4LXa4Z25HhzFiWCf7TlQmSqnt98pnuiHmzgY=
#         securityContext:
#           runAsNonRoot: true
#           runAsUser: 10001
#           capabilities:
#             drop:
#               - all
#           # readOnlyRootFilesystem: true
#         livenessProbe:
#           httpGet:
#             path: /
#             port: 8080
#           initialDelaySeconds: 300
#           periodSeconds: 3
#         readinessProbe:
#           httpGet:
#             path: /
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: laravel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: laravel
