---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_DATABASE
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_USERNAME
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secrets
              key: DB_PASSWORD
              optional: false
        ports:
        - containerPort: 5432
          name: postgres-port
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
      volumes:
        - name: pg-data
          emptyDir:
            medium: Memory 
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
        prometheus.io/scrape: 'false'
  labels:
    name: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    targetPort: postgres-port
  selector:
    name: postgres
