---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue
  template:
    metadata:
      labels:
        name: queue
    spec:
      containers:
      - name: queue
        image: steveoliver/laravel-roadrunner:v0.1.0
        command: ["php"]
        args: ["artisan", "horizon"]
        envFrom:
        - secretRef:
            name: laravel-secrets
      nodeSelector:
        kubernetes.io/os: linux
