---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
      annotations:
        prometheus.io.scrape: "false"
    spec:
      volumes:
      - name: redis-data
        emptyDir: {}
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server"]
        args: ["--requirepass", "redis_password"]
        volumeMounts:
          - name: redis-data
            mountPath: /data
        ports:
        - name: redis-port
          containerPort: 6379
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
spec:
  ports:
  - port: 6379
    targetPort: redis-port
  selector:
    name: redis
