apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-run
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: schedule-run
            image: steveoliver/laravel-roadrunner:v0.0.8
            imagePullPolicy: IfNotPresent
            command:
            - php
            - artisan
            - schedule:run
            envFrom:
            - secretRef:
                name: laravel-secrets
          nodeSelector:
            beta.kubernetes.io/os: linux
          restartPolicy: OnFailure
