---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: steveoliver/laravel-roadrunner:v0.0.8
        command: ["php"]
        args: ["artisan", "horizon"]
        volumes:
          - tmp-data:/tmp:rw
        envFrom:
        - secretRef:
          name: laravel-secrets
      nodeSelector:
        beta.kubernetes.io/os: linux
