---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
      - name: worker
        image: steveoliver/laravel-roadrunner:v0.0.8
        command: ["php"]
        args: ["artisan", "horizon"]
        envFrom:
        - secretRef:
            name: laravel-secrets
        volumeMounts:
        - name: tmp-data
          mountPath: /tmp
      volumes:
        - name: tmp-data
          emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
